email.joinWaitlist.subject=Welcome to the TurfClan Waitlist!
email.joinWaitlist.hero=You're on the list!
email.joinWaitlist.hello=Hello Athlete!
email.joinWaitlist.body=We have successfully received your request to join the waitlist. Welcome to the future of grassroots sports!
email.joinWaitlist.body2=We are building the ultimate professional stage for every athlete. Soon, you'll be able to book turfs, track your stats, and build your sports legacy—all in one place.
email.joinWaitlist.body3=Keep an eye on your inbox. We will notify you the moment we launch so you can get early access and be among the first to elevate your game.
email.signature.regards=Stay active,
email.signature.name=Your Turf Clan Team
email.footer.text1=We are on track to revolutionize sports in your city.
email.footer.text2=Made with ❤️ in India
email.footer.text3=&copy; 2026 All rights reserved.
email.disclaimer=This is an automatic generated email, please do not respond as the mail box isn't monitored.
