email.joinWaitlist.admin.subject=New Waitlist Entry: {0}
email.joinWaitlist.admin.hero=New Waitlist Entry
email.joinWaitlist.admin.hello=Hello Admin!
email.joinWaitlist.admin.body=A new user has joined the waitlist.
email.joinWaitlist.admin.userDetails=User Details:
email.signature.admin.regards=Stay active,
email.signature.admin.name=Your Turf Clan Team
email.footer.admin.text1=We are on track to revolutionize sports in your city.
email.footer.admin.text2=Made with ❤️ in India
email.footer.admin.text3=&copy; 2026 All rights reserved.
email.admin.disclaimer=This is an automatic generated email, please do not respond as the mail box isn't monitored.
