# Production Environment Configuration
server.port=${SERVER_PORT:8434}

# --- Logging Configuration ---
logging.level.root=INFO
logging.level.com.aerilontech.crm=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.springframework.jdbc.core=OFF
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR

# --- Database Configuration ---
spring.datasource.url=${AWS_RDS_URL}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}

# Connection Pooling (Crucial for Production)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000

# --- Hibernate/JPA Settings ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# --- Error Configuration ---
server.error.include-message=never
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false

spring.cloud.aws.s3.bucket=${S3_BUCKET_NAME}
spring.cloud.aws.region.static=${AWS_REGION}